module.exports = {
    FB_PAGE_TOKEN: '...',
    FB_VERIFY_TOKEN: '...',
    API_AI_CLIENT_ACCESS_TOKEN: '...',
    FB_APP_SECRET: '...',
    FB_APP_ID:'...',
    SERVER_URL: "",
    SENDGRID_API_KEY:"",
    EMAIL_FROM:"ozden@live.com",
    EMAIL_TO:"ozden@live.com",
    WEATHER_API_KEY:"",
    PG_CONFIG: {
        user:'',
        database: '',
        password: '',
        host: '....amazonaws.com',
        port: 5432,
        max: 100,
        idleTimeoutMillis: 3000,
    },
};
